# see https://github.com/golangci/golangci-lint#configuration
# https://raw.githubusercontent.com/NaturalSelectionLabs/RSS3-PreGod/develop/.golangci.yml
linters-settings:
  godot:
    exclude:
      - "^@*" # exclude swagger annotations
  tagliatelle:
    case:
      rules:
        json: snake
  lll:
    line-length: 150
  govet:
    check-shadowing: true
  unused:
    check-exported: true
  nolintlint:
    require-explanation: true
    require-specific: true
  misspell:
    # Correct spellings using locale preferences for US or UK.
    # Setting locale to US will correct the British spelling of 'colour' to 'color'.
    # Default is to use a neutral variety of English.
    locale: US
    ignore-words:
      - someword
  funlen:
    lines: 80
    statements: 50
  gomoddirectives:
    replace-allow-list:
      - github.com/elastic/go-elasticsearch/v7

linters: # https://golangci-lint.run/usage/linters
  disable:
    - godox # TODO comments should be allowed
    - gochecknoglobals # global vars should be allowed
    - gomnd # magic numbers should be allowed
    - scopelint # deprecated, replaced by exportloopref
    - gochecknoinits # `init` functions should be] allowed
    - gofumpt # too strict so far
    - paralleltest # Not for our situation
    - tparallel # Not for our situation
    - execinquery # https://github.com/golangci/golangci-lint/issues/2835
  enable:
    - exportloopref # in replacement of scopelint
    - deadcode # no dead code
    - gosimple # for simplified code
    - govet # reports suspicious constructs; e.g. Printf arguments alignment
    - ineffassign # no ineffective assignments
    - staticcheck # static analysis
    - structcheck # no unused struct fields
    - typecheck # type-checks Go code
    - unused # no unused vars, fns, etc.
    - varcheck # no unused global vars
    - nolintlint
    - misspell # finds commonly misspelled English words in comments
    - funlen
    - lll # reports long lines

  presets:
    - bugs
    - comment
    - complexity
    - error
    - format
    - import
    - metalinter
    - module
    - performance
    - sql
    - style
    - test
    - unused
  fast: true
