name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
        
    - name: Get Mods
      run: go install

    - name: Build_Linux_amd64
      run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o bridge_linux_amd64 -ldflags "-s -w"

    - name: Build_Windows_amd64
      run: CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -o bridge_windows_amd64.exe -ldflags "-s -w"

    - name: Build_Mac_amd64
      run: CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -o bridge_darwin_amd64 -ldflags "-s -w"
      
      

