name: Release

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      name:
        description: 'Manually release'
        required: false
        default: 'Mona the Octocat'

jobs:
   release:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.18
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Build
        run: make release

      - name: Pack
        run: bash "${{ github.workspace }}/.github/helpers/pack4release.sh"

      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "dist/*.tar.gz"
          generateReleaseNotes: true
          token: ${{ secrets.GITHUB_TOKEN }}